expected_movies_json = {
    "title": "Psy",
    "year": 1992,
    "released": "20 Nov 1992",
    "runtime": "104 min",
    "genre": "Action, Crime, Drama",
    "director": "Wladyslaw Pasikowski",
    "writer": "Wladyslaw Pasikowski",
    "actors": "Boguslaw Linda, Marek Kondrat, Cezary Pazura",
    "plot": "In the good old days Franz Maurer and his partners from the secret police used to live like kings. Now, they all must adapt to a new post-communist environment where they are scorned and losing all privileges. Some, like Franz, are like ordinary police fighting against drug dealers. But Franz will soon find out that some of his friends are on the other side.",
    "language": "Polish, English, German, Russian",
    "country": "Poland",
    "awards": "5 wins",
    "poster": "https://m.media-amazon.com/images/M/MV5BZGQwODdkOTctYWRlNC00ZjcyLWE4ZjctODQxZGVlM2YyMzViXkEyXkFqcGdeQXVyMjMwOTA0Ng@@._V1_SX300.jpg",
    "metascore": "N/A",
    "imdbRating": 7.6,
    "imdbID": "tt0105185",
}
