version: '3.9'

services:
  front:
    build: .
    container_name: frontend
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - movies_app_network
    volumes:
      - ./:/app

networks:
  movies_app_network:
    name: movies_app_network
