"""Add Movies Table

Revision ID: 4462a5818490
Revises:
Create Date: 2023-01-11 12:16:54.524129

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "4462a5818490"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("released", sa.String(), nullable=True),
        sa.Column("runtime", sa.String(), nullable=True),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("director", sa.String(), nullable=True),
        sa.Column("writer", sa.String(), nullable=True),
        sa.Column("actors", sa.String(), nullable=True),
        sa.Column("plot", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("awards", sa.String(), nullable=True),
        sa.Column("poster", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("metascore", sa.String(), nullable=True),
        sa.Column("imdbRating", sa.Float(), nullable=True),
        sa.Column("imdbID", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_id"), "movies", ["id"], unique=False)
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.drop_index(op.f("ix_movies_id"), table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
