"""set imdbid to unique

Revision ID: c302710ea723
Revises: 4462a5818490
Create Date: 2023-01-11 12:18:26.832461

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c302710ea723"
down_revision = "4462a5818490"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "movies", ["imdbID"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movies", type_="unique")
    # ### end Alembic commands ###
