"""Add Favourite Table and relationship

Revision ID: d9082bb9079a
Revises: c302710ea723
Create Date: 2023-01-17 10:07:37.857973

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9082bb9079a"
down_revision = "c302710ea723"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favourites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_favourites_id"), "favourites", ["id"], unique=False)
    op.create_index(
        op.f("ix_favourites_user_id"), "favourites", ["user_id"], unique=False
    )
    op.drop_index("ix_movies_title", table_name="movies")
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.create_index("ix_movies_title", "movies", ["title"], unique=False)
    op.drop_index(op.f("ix_favourites_user_id"), table_name="favourites")
    op.drop_index(op.f("ix_favourites_id"), table_name="favourites")
    op.drop_table("favourites")
    # ### end Alembic commands ###
