variables:
  DOCKER_REGISTRY: 682423865936.dkr.ecr.eu-central-1.amazonaws.com
  REGION: eu-central-1
  REGISTRY_NAME: movies
  SECURE_FILES_DOWNLOAD_PATH: './'



default:
  image: docker:latest
  before_script:
    - apk add curl bash
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
    - echo "Building image..."
    - docker build -t $DOCKER_REGISTRY/$REGISTRY_NAME:$IMAGE_TAG .



services:
  - docker:dind

cache:
  key:
    files:
      - Pipfile.lock
  paths:
    - .cache/

stages:
  - code_analize
  - test
  - build

black:
  inherit:
    default: true
  stage: code_analize
  script:
    - docker run $DOCKER_REGISTRY/$REGISTRY_NAME:$IMAGE_TAG black --check .

unit_tests:
  inherit:
    default: true
  stage: test
  script:
    - docker run $DOCKER_REGISTRY/$REGISTRY_NAME:$IMAGE_TAG python -m pytest tests/unit

integration_tests:
  inherit:
    default: true
  stage: test
  script:
    - docker run $DOCKER_REGISTRY/$REGISTRY_NAME:$IMAGE_TAG python -m pytest tests/integration

build:
  stage: build
  inherit:
    default: true
  script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password --region "${REGION}"  | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - echo "Pushing image..."
    - docker push $DOCKER_REGISTRY/$REGISTRY_NAME:$IMAGE_TAG
  only:
    - prod
