version: "3.9"
services:
  movies:
    container_name: movies
    build: .
    ports:
      - "8001:8000"
    environment:
      - DEBUG=true
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - movies_network
      - db_network
    command: bash -c "python wait_for_postgres.py && alembic upgrade head && uvicorn --host=0.0.0.0 --port=8000 src.main:app --reload"

networks:
  movies_network:
    name: movies_network
  db_network:
    external: true
